//! Generic asynchronous implementation.
//!
//! This module contains generic definitions for functions using arbitrary asynchronous runtimes.
//! The [`crossmist::tokio`] and [`crossmist::smol`] modules provides type and functions definitions
//! for their respective runtimes. You should probably use those.
//!
//!
//! ## Channels
//!
//! Asynchronous channels work just like synchronous channels except that you need to add `.await`
//! to each blocking call. Synchronous and asynchronous channels can be converted to each other.
//! This might be useful if you use tokio/smol in the parent process but use synchronous code in the
//! child. In this case, you would create a channel using [`crossmist::channel`] and convert one
//! side to an asynchronous one.
//!
//!
//! ## Processes
//!
//! To start a child process, you use any of the `spawn_tokio` and `spawn_smol` methods generated by
//! `#[crossmist::entrypoint]`:
//!
//! ```ignore
//! #[crossmist::entrypoint]
//! fn my_process() {
//!     ...
//! }
//!
//! let child = my_process.spawn_tokio().await?;
//! // let child = my_process.spawn_smol().await?;
//! ```
//!
//! Note that you can use these methods on both synchronous and asynchronous functions, e.g. the
//! following works too:
//!
//! ```ignore
//! #[crossmist::entrypoint(tokio)]
//! async fn my_process() {
//!     ...
//! }
//!
//! let child = my_process.spawn_tokio().await?;
//! ```

use crate::{Deserializer, Object, Serializer, StaticFn, imp, subprocess};
use std::fmt;
use std::future::Future;
use std::io::{Error, ErrorKind, Result};
use std::marker::PhantomData;
use std::sync::{Arc, Mutex};
#[cfg(unix)]
use {
    crate::internals::{SingleObjectReceiver, SingleObjectSender, socketpair},
    std::os::unix::io::{AsFd, AsRawFd, FromRawFd, IntoRawFd, OwnedFd, RawFd},
};
#[cfg(windows)]
use {
    crate::internals::{deserialize_with_handles, serialize_with_handles, socketpair},
    std::os::windows::io::{
        AsRawHandle, AsRawSocket, AsSocket, FromRawSocket, IntoRawSocket, OwnedHandle, OwnedSocket,
        RawSocket,
    },
    windows::Win32::{Foundation::HANDLE, System::Threading},
};

#[cfg(unix)]
pub(crate) type SyncStream = std::os::unix::net::UnixStream;
// This is a complete lie and a fabrication, but `std::os::windows::net::UnixStream` is unstable and
// `TcpStream` is close enough.
#[cfg(windows)]
pub(crate) type SyncStream = std::net::TcpStream;

/// Runtime-dependent stream implementation.
#[cfg(unix)]
pub unsafe trait AsyncStream: Object + AsFd + AsRawFd + Sized {
    /// Create the stream from a sync stream.
    fn try_new(stream: SyncStream) -> Result<Self>;

    /// Whether socket operations should be blocking.
    const IS_BLOCKING: bool;

    /// Perform a blocking write.
    ///
    /// Calls `f`. If it returns `Err(WouldBlock)`, waits until the stream is writable and retries.
    /// When the function returns anything other than `Err(WouldBlock)`, returns.
    fn blocking_write<T>(
        &self,
        f: impl FnMut() -> Result<T> + Send,
    ) -> impl Future<Output = Result<T>> + Send;

    /// Perform a blocking read.
    ///
    /// Calls `f`. If it returns `Err(WouldBlock)`, waits until the stream is readable and retries.
    /// When the function returns anything other than `Err(WouldBlock)`, returns.
    fn blocking_read<T>(
        &self,
        f: impl FnMut() -> Result<T> + Send,
    ) -> impl Future<Output = Result<T>> + Send;
}

/// Runtime-dependent stream implementation.
#[cfg(windows)]
pub unsafe trait AsyncStream: Object + AsSocket + AsRawSocket + Sized {
    /// Create the stream from a sync stream.
    fn try_new(stream: SyncStream) -> Result<Self>;

    /// Perform a write.
    #[cfg(windows)]
    fn write(&mut self, buf: &[u8]) -> impl Future<Output = Result<()>> + Send;

    /// Perform a read.
    #[cfg(windows)]
    fn read(&mut self, buf: &mut [u8]) -> impl Future<Output = Result<()>> + Send;
}

/// The transmitting side of a unidirectional channel.
///
/// `T` is the type of the objects this side sends via the channel and the other side receives.
#[derive(Object)]
#[crossmist(bound = "Stream: Object")]
pub struct Sender<Stream, T> {
    pub(crate) fd: Stream,
    marker: PhantomData<fn(T)>,
}

/// The receiving side of a unidirectional channel.
///
/// `T` is the type of the objects the other side sends via the channel and this side receives.
#[derive(Object)]
#[crossmist(bound = "Stream: Object")]
pub struct Receiver<Stream, T> {
    pub(crate) fd: Stream,
    marker: PhantomData<fn() -> T>,
}

/// A side of a bidirectional channel.
///
/// `S` is the type of the objects this side sends via the channel and the other side receives, `R`
/// is the type of the objects the other side sends via the channel and this side receives.
#[derive(Object)]
#[crossmist(bound = "Stream: Object")]
pub struct Duplex<Stream, S, R> {
    pub(crate) fd: Stream,
    marker: PhantomData<fn(S) -> R>,
}

/// Create a unidirectional channel.
pub fn channel<Stream: AsyncStream, T>() -> Result<(Sender<Stream, T>, Receiver<Stream, T>)> {
    let (tx, rx) = duplex::<Stream, T, T>()?;
    Ok((tx.into_sender(), rx.into_receiver()))
}

/// Create a bidirectional channel.
pub fn duplex<Stream: AsyncStream, A, B>() -> Result<(Duplex<Stream, A, B>, Duplex<Stream, B, A>)> {
    let (tx, rx) = socketpair()?;
    unsafe {
        Ok((
            Duplex::from_stream(Stream::try_new(tx)?),
            Duplex::from_stream(Stream::try_new(rx)?),
        ))
    }
}

impl<Stream, T> Sender<Stream, T> {
    pub(crate) unsafe fn from_stream(fd: Stream) -> Self {
        Sender {
            fd,
            marker: PhantomData,
        }
    }

    /// Send a value to the other side.
    pub async fn send(&mut self, value: T) -> Result<()>
    where
        Stream: AsyncStream,
        T: Object,
    {
        #[cfg(unix)]
        {
            let mut sender = SingleObjectSender::new(self.fd.as_fd(), value, Stream::IS_BLOCKING);
            self.fd.blocking_write(|| sender.send_next()).await
        }
        #[cfg(windows)]
        {
            let serialized = serialize_with_handles(value)?;
            self.fd.write(&serialized.len().to_ne_bytes()).await?;
            self.fd.write(&serialized).await
        }
    }
}

impl<Stream: fmt::Debug, T> fmt::Debug for Sender<Stream, T> {
    fn fmt(&self, fmt: &mut fmt::Formatter) -> fmt::Result {
        fmt.debug_tuple("Sender").field(&self.fd).finish()
    }
}

impl<Stream: AsyncStream, T> TryFrom<crate::Sender<T>> for Sender<Stream, T> {
    type Error = Error;
    fn try_from(value: crate::Sender<T>) -> Result<Self> {
        unsafe { Ok(Self::from_stream(Stream::try_new(value.0.fd.0)?)) }
    }
}

#[cfg(unix)]
impl<Stream: AsyncStream, T> AsRawFd for Sender<Stream, T> {
    fn as_raw_fd(&self) -> RawFd {
        self.fd.as_raw_fd()
    }
}
#[cfg(windows)]
impl<Stream: AsyncStream, T> AsRawSocket for Sender<Stream, T> {
    fn as_raw_socket(&self) -> RawSocket {
        self.fd.as_raw_socket()
    }
}

impl<Stream, T> Receiver<Stream, T> {
    pub(crate) unsafe fn from_stream(fd: Stream) -> Self {
        Receiver {
            fd,
            marker: PhantomData,
        }
    }

    /// Receive a value from the other side.
    ///
    /// Returns `Ok(None)` if the other side has dropped the channel.
    pub async fn recv(&mut self) -> Result<Option<T>>
    where
        Stream: AsyncStream,
        T: Object,
    {
        #[cfg(unix)]
        {
            let mut receiver =
                unsafe { SingleObjectReceiver::new(self.fd.as_fd(), Stream::IS_BLOCKING) };
            self.fd.blocking_read(|| receiver.recv_next()).await
        }
        #[cfg(windows)]
        {
            let mut len = [0u8; size_of::<usize>()];
            if let Err(e) = self.fd.read(&mut len).await {
                if let ErrorKind::UnexpectedEof | ErrorKind::ConnectionReset = e.kind() {
                    return Ok(None);
                }
                return Err(e);
            }
            let len = usize::from_ne_bytes(len);

            let mut serialized = vec![0u8; len];
            self.fd.read(&mut serialized).await?;
            unsafe { deserialize_with_handles(serialized) }.map(Some)
        }
    }
}

impl<Stream: fmt::Debug, T> fmt::Debug for Receiver<Stream, T> {
    fn fmt(&self, fmt: &mut fmt::Formatter) -> fmt::Result {
        fmt.debug_tuple("Receiver").field(&self.fd).finish()
    }
}

impl<Stream: AsyncStream, T> TryFrom<crate::Receiver<T>> for Receiver<Stream, T> {
    type Error = Error;
    fn try_from(value: crate::Receiver<T>) -> Result<Self> {
        unsafe { Ok(Self::from_stream(Stream::try_new(value.0.fd.0)?)) }
    }
}

#[cfg(unix)]
impl<Stream: AsyncStream, T> AsRawFd for Receiver<Stream, T> {
    fn as_raw_fd(&self) -> RawFd {
        self.fd.as_raw_fd()
    }
}
#[cfg(windows)]
impl<Stream: AsyncStream, T> AsRawSocket for Receiver<Stream, T> {
    fn as_raw_socket(&self) -> RawSocket {
        self.fd.as_raw_socket()
    }
}

impl<Stream, S, R> Duplex<Stream, S, R> {
    pub(crate) unsafe fn from_stream(fd: Stream) -> Self {
        Duplex {
            fd,
            marker: PhantomData,
        }
    }

    /// Send a value to the other side.
    pub async fn send(&mut self, value: S) -> Result<()>
    where
        Stream: AsyncStream,
        S: Object,
    {
        #[cfg(unix)]
        {
            let mut sender = SingleObjectSender::new(self.fd.as_fd(), value, Stream::IS_BLOCKING);
            self.fd.blocking_write(|| sender.send_next()).await
        }
        #[cfg(windows)]
        {
            let serialized = serialize_with_handles(value)?;
            self.fd.write(&serialized.len().to_ne_bytes()).await?;
            self.fd.write(&serialized).await
        }
    }

    /// Receive a value from the other side.
    ///
    /// Returns `Ok(None)` if the other side has dropped the channel.
    pub async fn recv(&mut self) -> Result<Option<R>>
    where
        Stream: AsyncStream,
        R: Object,
    {
        #[cfg(unix)]
        {
            let mut receiver =
                unsafe { SingleObjectReceiver::new(self.fd.as_fd(), Stream::IS_BLOCKING) };
            self.fd.blocking_read(|| receiver.recv_next()).await
        }
        #[cfg(windows)]
        {
            let mut len = [0u8; size_of::<usize>()];
            if let Err(e) = self.fd.read(&mut len).await {
                if let ErrorKind::UnexpectedEof | ErrorKind::ConnectionReset = e.kind() {
                    return Ok(None);
                }
                return Err(e);
            }
            let len = usize::from_ne_bytes(len);

            let mut serialized = vec![0u8; len];
            self.fd.read(&mut serialized).await?;
            unsafe { deserialize_with_handles(serialized) }.map(Some)
        }
    }

    /// Send a value from the other side and wait for a response immediately.
    ///
    /// If the other side closes the channel before responding, an error is returned.
    pub async fn request(&mut self, value: S) -> Result<R>
    where
        Stream: AsyncStream,
        S: Object,
        R: Object,
    {
        self.send(value).await?;
        self.recv().await?.ok_or_else(|| {
            Error::new(
                ErrorKind::UnexpectedEof,
                "The subprocess exitted before responding to the request",
            )
        })
    }

    pub fn into_sender(self) -> Sender<Stream, S> {
        unsafe { Sender::from_stream(self.fd) }
    }

    pub fn into_receiver(self) -> Receiver<Stream, R> {
        unsafe { Receiver::from_stream(self.fd) }
    }
}

impl<Stream: fmt::Debug, S, R> fmt::Debug for Duplex<Stream, S, R> {
    fn fmt(&self, fmt: &mut fmt::Formatter) -> fmt::Result {
        fmt.debug_tuple("Duplex").field(&self.fd).finish()
    }
}

impl<Stream: AsyncStream, S, R> TryFrom<crate::Duplex<S, R>> for Duplex<Stream, S, R> {
    type Error = Error;
    fn try_from(value: crate::Duplex<S, R>) -> Result<Self> {
        unsafe { Ok(Self::from_stream(Stream::try_new(value.0.fd.0)?)) }
    }
}

#[cfg(unix)]
impl<Stream: AsyncStream, S, R> AsRawFd for Duplex<Stream, S, R> {
    fn as_raw_fd(&self) -> RawFd {
        self.fd.as_raw_fd()
    }
}
#[cfg(windows)]
impl<Stream: AsyncStream, S, R> AsRawSocket for Duplex<Stream, S, R> {
    fn as_raw_socket(&self) -> RawSocket {
        self.fd.as_raw_socket()
    }
}

#[cfg(unix)]
type ProcHandle = rustix::process::Pid;
#[cfg(windows)]
type ProcHandle = OwnedHandle;

#[cfg(unix)]
pub(crate) type ProcID = rustix::process::RawPid;
#[cfg(windows)]
pub(crate) type ProcID = HANDLE;

/// A subprocess.
pub struct Child<Stream, T> {
    pub(crate) proc_handle: ProcHandle,
    output_rx: Receiver<Stream, T>,
    may_kill: Arc<Mutex<bool>>,
}

/// A handle that allows to kill the process.
pub struct KillHandle {
    proc_id: ProcID,
    may_kill: Arc<Mutex<bool>>,
}

unsafe impl Send for KillHandle {}
unsafe impl Sync for KillHandle {}

impl<Stream, T> Child<Stream, T> {
    fn new(proc_handle: ProcHandle, output_rx: Receiver<Stream, T>) -> Child<Stream, T> {
        Child {
            proc_handle,
            output_rx,
            may_kill: Arc::new(Mutex::new(true)),
        }
    }

    /// Get a handle for process termination.
    pub fn get_kill_handle(&self) -> crate::KillHandle {
        KillHandle {
            proc_id: self.id(),
            may_kill: self.may_kill.clone(),
        }
    }

    /// Get ID of the process.
    pub fn id(&self) -> ProcID {
        #[cfg(unix)]
        {
            rustix::process::Pid::as_raw(Some(self.proc_handle))
        }
        #[cfg(windows)]
        {
            HANDLE(self.proc_handle.as_raw_handle())
        }
    }

    /// Wait for the process to finish and obtain the value it returns.
    ///
    /// An error is returned if the process panics or is terminated. An error is also delivered if
    /// it exits via [`std::process::exit`] or alike instead of returning a value, unless the return
    /// type is `()`. In that case, `Ok(())` is returned.
    pub async fn join(mut self) -> Result<T>
    where
        Stream: AsyncStream,
        T: Object,
    {
        let mut value = self.output_rx.recv().await?;
        if typeid::of::<T>() == typeid::of::<()>() {
            // Functions returning `()` don't submit their results explicitly; see the explanation
            // in `spawn` for more detail. This read effectively transmutes `()` to `T`.
            value = Some(unsafe { std::ptr::dangling::<T>().read() });
        }
        let mut guard = self.may_kill.lock().expect("Kill mutex is poisoned");
        *guard = false;
        // This is synchronous, but should be really fast
        #[cfg(unix)]
        {
            let (_pid, status) = rustix::process::waitpid(
                Some(self.proc_handle),
                rustix::process::WaitOptions::empty(),
            )?
            .unwrap();
            if status.exit_status() == Some(0) {
                value.ok_or_else(|| {
                    Error::other("The subprocess terminated without returning a value")
                })
            } else {
                Err(Error::other(format!(
                    "The subprocess did not terminate successfully: {status:?}"
                )))
            }
        }
        #[cfg(windows)]
        {
            if unsafe {
                Threading::WaitForSingleObject(
                    HANDLE(self.proc_handle.as_raw_handle()),
                    Threading::INFINITE,
                )
            }
            .0 == u32::MAX
            {
                return Err(Error::last_os_error());
            }
            let mut code: u32 = 0;
            unsafe {
                Threading::GetExitCodeProcess(
                    HANDLE(self.proc_handle.as_raw_handle()),
                    &mut code as *mut u32,
                )?;
            }
            if code == 0 {
                value.ok_or_else(|| {
                    Error::other("The subprocess terminated without returning a value")
                })
            } else {
                Err(Error::other(format!(
                    "The subprocess terminated with exit code {code}"
                )))
            }
        }
    }
}

impl<Stream: fmt::Debug, T> fmt::Debug for Child<Stream, T> {
    fn fmt(&self, fmt: &mut fmt::Formatter) -> fmt::Result {
        fmt.debug_struct("Child")
            .field("proc_handle", &self.proc_handle)
            .field("output_rx", &self.output_rx)
            .finish()
    }
}

impl KillHandle {
    /// Terminate the process immediately.
    pub fn kill(&self) -> Result<()> {
        let guard = self.may_kill.lock().expect("Kill mutex is poisoned");
        if !*guard {
            return Err(std::io::Error::other(
                "This process has already been joined",
            ));
        }
        #[cfg(unix)]
        rustix::process::kill_process(
            rustix::process::Pid::from_raw(self.proc_id).unwrap(),
            rustix::process::Signal::KILL,
        )?;
        #[cfg(windows)]
        unsafe {
            Threading::TerminateProcess(self.proc_id, 1)?;
        }
        Ok(())
    }
}

impl fmt::Debug for KillHandle {
    fn fmt(&self, fmt: &mut fmt::Formatter) -> fmt::Result {
        fmt.debug_struct("KillHandle")
            .field("proc_id", &self.proc_id)
            .finish()
    }
}

pub(crate) async unsafe fn spawn<
    Stream: AsyncStream,
    Func: FnOnce(Box<dyn FnOnce() -> Args>) -> Ret,
    Args: Object,
    Ret: Object,
>(
    _func: Func,
    args: Args,
) -> Result<Child<Stream, Ret>> {
    unsafe {
        imp::perform_sanity_checks();

        let entrypoint = |mut deserializer: Deserializer,
                          #[cfg(unix)] channel: OwnedFd,
                          #[cfg(windows)] channel: OwnedSocket| {
            // Re-read `func` so that we don't borrow anything and `entrypoint` can be converted to
            // a function pointer.
            let func = core::ptr::dangling::<Func>().read();
            let output = func(Box::new(move || deserializer.deserialize()));

            // Avoid explicitly sending a `()` result. This allows functions that call
            // `std::process::exit(0)` to exit cleanly, and acts as an optimization as a bonus. We
            // don't handle other ZSTs here, since some ZSTs cannot be constructed safely, while
            // this interaction would allow them to be conjured.
            if typeid::of::<Ret>() == typeid::of::<()>() {
                return;
            }

            // Even if the function was asynchronous, there shouldn't be any task running at this
            // moment, so it is fine (and more efficient) to use a sync sender
            #[cfg(unix)]
            let mut channel = crate::Sender::from_raw_fd(channel.into_raw_fd());
            #[cfg(windows)]
            let mut channel = crate::Sender::from_raw_socket(channel.into_raw_socket());
            channel
                .send(output)
                .expect("Failed to send subprocess output");
        };

        let entrypoint = StaticFn::new_unchecked(entrypoint as fn(_, _));

        let (local, child) = crate::duplex()?;
        let mut local: Duplex<Stream, _, Ret> = local.try_into()?;

        let process_handle;

        // Send fds/handles/sockets via a channel instead of inheritance, because:
        // - On Linux, the child already uses `recvmsg` to retrieve the input, so passing fds that
        //   way is free.
        // - On Windows, there is no good way to inherit handles without races, so we have to pass
        //   them via the broker anyway.
        #[cfg(unix)]
        {
            process_handle = subprocess::_spawn_child(child.0.fd.as_fd())?;
        }

        #[cfg(windows)]
        {
            process_handle = subprocess::_spawn_child(child.0.fd.as_socket())?;
            // Wait for a response that the handles have been copied successfully before continuing.
            let mut signal = Receiver::<Stream, ()>::from_stream(local.fd);
            signal.recv().await?;
            local.fd = signal.fd;
        }

        local.send((entrypoint, args)).await?;

        let receiver = Receiver::from_stream(local.fd);
        Ok(Child::new(process_handle, receiver))
    }
}

pub(crate) fn handle_entry(
    #[cfg(unix)] channel: OwnedFd,
    #[cfg(windows)] channel: OwnedSocket,
) -> ! {
    // XXX: very hacky
    struct FakeDeserializer(Deserializer);
    unsafe impl Object for FakeDeserializer {
        fn serialize_self(self, _serializer: &mut Serializer) {
            unreachable!()
        }
        unsafe fn deserialize_self(deserializer: &mut Deserializer) -> Self {
            Self(core::mem::replace(
                deserializer,
                Deserializer::from(Serializer::new()),
            ))
        }
    }

    #[cfg(unix)]
    let mut rx = unsafe { crate::Receiver::from_raw_fd(channel.as_raw_fd()) };
    #[cfg(windows)]
    let mut rx = unsafe { crate::Receiver::from_raw_socket(channel.as_raw_socket()) };

    let deserializer: FakeDeserializer = rx
        .recv()
        .expect("failed to read entry for crossmist")
        .expect("no entry passed");
    let mut deserializer = deserializer.0;
    core::mem::forget(rx);

    let entry: StaticFn<fn(_, _)> = unsafe { deserializer.deserialize() };
    entry(deserializer, channel);
    std::process::exit(0);
}
