//! Generic asynchronous implementation.
//!
//! This module contains generic definitions for functions using arbitrary asynchronous runtimes.
//! The [`crossmist::tokio`] and [`crossmist::smol`] modules provides type and functions definitions
//! for their respective runtimes. You should probably use those.
//!
//!
//! ## Channels
//!
//! Asynchronous channels work just like synchronous channels except that you need to add `.await`
//! to each blocking call. Synchronous and asynchronous channels can be converted to each other.
//! This might be useful if you use tokio/smol in the parent process but use synchronous code in the
//! child. In this case, you would create a channel using [`crossmist::channel`] and convert one
//! side to an asynchronous one.
//!
//!
//! ## Processes
//!
//! To start a child process, you use any of the `spawn_tokio` and `spawn_smol` methods generated by
//! `#[func]`:
//!
//! ```ignore
//! #[func]
//! fn my_process() {
//!     ...
//! }
//!
//! let child = my_process.spawn_tokio().await?;
//! // let child = my_process.spawn_smol().await?;
//! ```
//!
//! Note that you can use these methods on both synchronous and asynchronous functions, e.g. the
//! following works too:
//!
//! ```ignore
//! #[func(tokio)]
//! async fn my_process() {
//!     ...
//! }
//!
//! let child = my_process.spawn_tokio().await?;
//! ```

use crate::{
    handles::{FromRawHandle, IntoRawHandle, RawHandle},
    imp,
    ipc::SyncStream,
    subprocess, FnOnceObject, Object, Serializer,
};
use std::future::Future;
use std::io::{Error, ErrorKind, Result};
use std::marker::PhantomData;
#[cfg(unix)]
use {
    crate::internals::{socketpair, SingleObjectReceiver, SingleObjectSender},
    nix::libc::pid_t,
};
#[cfg(windows)]
use {
    crate::{
        handles::AsRawHandle,
        internals::{deserialize_with_handles, serialize_with_handles},
    },
    std::os::windows::io,
    windows::Win32::System::{Pipes, Threading, WindowsProgramming},
};

/// Runtime-dependent stream implementation.
pub unsafe trait AsyncStream: Object + Sized {
    /// Create the stream from a sync stream.
    fn try_new(stream: SyncStream) -> Result<Self>;

    /// Get a raw handle to the underlying stream.
    fn as_raw_handle(&self) -> RawHandle;

    /// Whether socket operations should be blocking.
    #[cfg(unix)]
    const IS_BLOCKING: bool;

    /// Perform a blocking write.
    ///
    /// Calls `f`. If it returns `Err(WouldBlock)`, waits until the stream is writable and retries.
    /// When the function returns anything other than `Err(WouldBlock)`, returns.
    #[cfg(unix)]
    fn blocking_write<T>(
        &self,
        f: impl FnMut() -> Result<T> + Send,
    ) -> impl Future<Output = Result<T>> + Send;
    /// Perform a write.
    #[cfg(windows)]
    fn write(&mut self, buf: &[u8]) -> impl Future<Output = Result<()>> + Send;

    /// Perform a blocking read.
    ///
    /// Calls `f`. If it returns `Err(WouldBlock)`, waits until the stream is readable and retries.
    /// When the function returns anything other than `Err(WouldBlock)`, returns.
    #[cfg(unix)]
    fn blocking_read<T>(
        &self,
        f: impl FnMut() -> Result<T> + Send,
    ) -> impl Future<Output = Result<T>> + Send;
    /// Perform a read.
    #[cfg(windows)]
    fn read(&mut self, buf: &mut [u8]) -> impl Future<Output = Result<()>> + Send;
}

/// The transmitting side of a unidirectional channel.
///
/// `T` is the type of the objects this side sends via the channel and the other side receives.
#[derive(Object)]
pub struct Sender<Stream: AsyncStream, T: Object> {
    fd: Stream,
    marker: PhantomData<fn(T)>,
}

/// The receiving side of a unidirectional channel.
///
/// `T` is the type of the objects the other side sends via the channel and this side receives.
#[derive(Object)]
pub struct Receiver<Stream: AsyncStream, T: Object> {
    fd: Stream,
    marker: PhantomData<fn() -> T>,
}

/// A side of a bidirectional channel.
///
/// `S` is the type of the objects this side sends via the channel and the other side receives, `R`
/// is the type of the objects the other side sends via the channel and this side receives.
#[derive(Object)]
pub struct Duplex<Stream: AsyncStream, S: Object, R: Object> {
    #[cfg(unix)]
    fd: Stream,
    #[cfg(unix)]
    marker: PhantomData<fn(S) -> R>,
    #[cfg(windows)]
    pub(crate) sender: Sender<Stream, S>,
    #[cfg(windows)]
    pub(crate) receiver: Receiver<Stream, R>,
}

/// Create a unidirectional channel.
pub fn channel<Stream: AsyncStream, T: Object>() -> Result<(Sender<Stream, T>, Receiver<Stream, T>)>
{
    #[cfg(unix)]
    {
        let (tx, rx) = duplex::<Stream, T, T>()?;
        Ok((tx.into_sender(), rx.into_receiver()))
    }
    #[cfg(windows)]
    {
        let mut tx: RawHandle = Default::default();
        let mut rx: RawHandle = Default::default();
        unsafe {
            Pipes::CreatePipe(
                &mut rx as *mut RawHandle,
                &mut tx as *mut RawHandle,
                std::ptr::null(),
                0,
            )
            .ok()?;
        }
        let tx = unsafe { SyncStream::from_raw_handle(tx) };
        let rx = unsafe { SyncStream::from_raw_handle(rx) };
        let tx = Sender {
            fd: Stream::try_new(tx)?,
            marker: PhantomData,
        };
        let rx = Receiver {
            fd: Stream::try_new(rx)?,
            marker: PhantomData,
        };
        Ok((tx, rx))
    }
}

/// Create a bidirectional channel.
pub fn duplex<Stream: AsyncStream, A: Object, B: Object>(
) -> Result<(Duplex<Stream, A, B>, Duplex<Stream, B, A>)> {
    #[cfg(unix)]
    {
        let (tx, rx) = socketpair(0)?;
        unsafe {
            Ok((
                Duplex::from_stream(Stream::try_new(tx)?),
                Duplex::from_stream(Stream::try_new(rx)?),
            ))
        }
    }
    #[cfg(windows)]
    {
        let (tx_a, rx_a) = channel::<Stream, A>()?;
        let (tx_b, rx_b) = channel::<Stream, B>()?;
        let ours = Duplex {
            sender: tx_a,
            receiver: rx_b,
        };
        let theirs = Duplex {
            sender: tx_b,
            receiver: rx_a,
        };
        Ok((ours, theirs))
    }
}

impl<Stream: AsyncStream, T: Object> Sender<Stream, T> {
    pub(crate) unsafe fn from_stream(fd: Stream) -> Self {
        Sender {
            fd,
            marker: PhantomData,
        }
    }

    /// Send a value to the other side.
    pub async fn send(&mut self, value: &T) -> Result<()> {
        #[cfg(unix)]
        {
            let mut sender =
                SingleObjectSender::new(self.fd.as_raw_handle(), value, Stream::IS_BLOCKING);
            self.fd.blocking_write(|| sender.send_next()).await
        }
        #[cfg(windows)]
        {
            let serialized = serialize_with_handles(value)?;
            self.fd.write(&serialized.len().to_ne_bytes()).await?;
            self.fd.write(&serialized).await
        }
    }
}

impl<Stream: AsyncStream, T: Object> TryFrom<crate::Sender<T>> for Sender<Stream, T> {
    type Error = Error;
    fn try_from(value: crate::Sender<T>) -> Result<Self> {
        unsafe {
            Ok(Self::from_stream(Stream::try_new(
                SyncStream::from_raw_handle(value.into_raw_handle()),
            )?))
        }
    }
}
impl<Stream: AsyncStream, T: Object> From<Sender<Stream, T>> for crate::Sender<T> {
    fn from(value: Sender<Stream, T>) -> Self {
        unsafe { Self::from_raw_handle(value.into_raw_handle()) }
    }
}

#[cfg(unix)]
impl<Stream: AsyncStream, T: Object> std::os::unix::io::AsRawFd for Sender<Stream, T> {
    fn as_raw_fd(&self) -> RawHandle {
        self.fd.as_raw_handle()
    }
}
#[cfg(windows)]
impl<Stream: AsyncStream, T: Object> io::AsRawHandle for Sender<Stream, T> {
    fn as_raw_handle(&self) -> std::os::windows::prelude::RawHandle {
        self.fd.as_raw_handle().0 as _
    }
}

#[cfg(unix)]
impl<Stream: AsyncStream, T: Object> std::os::unix::io::IntoRawFd for Sender<Stream, T> {
    fn into_raw_fd(self) -> RawHandle {
        let fd = self.fd.as_raw_handle();
        std::mem::forget(self);
        fd
    }
}
#[cfg(windows)]
impl<Stream: AsyncStream, T: Object> std::os::windows::prelude::IntoRawHandle
    for Sender<Stream, T>
{
    fn into_raw_handle(self) -> std::os::windows::prelude::RawHandle {
        let fd = io::AsRawHandle::as_raw_handle(&self);
        std::mem::forget(self);
        fd
    }
}

impl<Stream: AsyncStream, T: Object> Receiver<Stream, T> {
    pub(crate) unsafe fn from_stream(fd: Stream) -> Self {
        Receiver {
            fd,
            marker: PhantomData,
        }
    }

    /// Receive a value from the other side.
    ///
    /// Returns `Ok(None)` if the other side has dropped the channel.
    pub async fn recv(&mut self) -> Result<Option<T>> {
        #[cfg(unix)]
        {
            let mut receiver =
                unsafe { SingleObjectReceiver::new(self.fd.as_raw_handle(), Stream::IS_BLOCKING) };
            self.fd.blocking_read(|| receiver.recv_next()).await
        }
        #[cfg(windows)]
        {
            let mut len = [0u8; std::mem::size_of::<usize>()];
            if let Err(e) = self.fd.read(&mut len).await {
                if e.kind() == ErrorKind::UnexpectedEof {
                    return Ok(None);
                }
                return Err(e);
            }
            let len = usize::from_ne_bytes(len);

            let mut serialized = vec![0u8; len];
            self.fd.read(&mut serialized).await?;

            unsafe { deserialize_with_handles(serialized).map(Some) }
        }
    }
}

impl<Stream: AsyncStream, T: Object> TryFrom<crate::Receiver<T>> for Receiver<Stream, T> {
    type Error = Error;
    fn try_from(value: crate::Receiver<T>) -> Result<Self> {
        unsafe {
            Ok(Self::from_stream(Stream::try_new(
                SyncStream::from_raw_handle(value.into_raw_handle()),
            )?))
        }
    }
}
impl<Stream: AsyncStream, T: Object> From<Receiver<Stream, T>> for crate::Receiver<T> {
    fn from(value: Receiver<Stream, T>) -> Self {
        unsafe { Self::from_raw_handle(value.into_raw_handle()) }
    }
}

#[cfg(unix)]
impl<Stream: AsyncStream, T: Object> std::os::unix::io::AsRawFd for Receiver<Stream, T> {
    fn as_raw_fd(&self) -> RawHandle {
        self.fd.as_raw_handle()
    }
}
#[cfg(windows)]
impl<Stream: AsyncStream, T: Object> io::AsRawHandle for Receiver<Stream, T> {
    fn as_raw_handle(&self) -> std::os::windows::prelude::RawHandle {
        self.fd.as_raw_handle().0 as _
    }
}

#[cfg(unix)]
impl<Stream: AsyncStream, T: Object> std::os::unix::io::IntoRawFd for Receiver<Stream, T> {
    fn into_raw_fd(self) -> RawHandle {
        let fd = self.fd.as_raw_handle();
        std::mem::forget(self);
        fd
    }
}
#[cfg(windows)]
impl<Stream: AsyncStream, T: Object> std::os::windows::prelude::IntoRawHandle
    for Receiver<Stream, T>
{
    fn into_raw_handle(self) -> std::os::windows::prelude::RawHandle {
        let fd = io::AsRawHandle::as_raw_handle(&self);
        std::mem::forget(self);
        fd
    }
}

impl<Stream: AsyncStream, S: Object, R: Object> Duplex<Stream, S, R> {
    #[cfg(unix)]
    pub(crate) unsafe fn from_stream(fd: Stream) -> Self {
        Duplex {
            fd,
            marker: PhantomData,
        }
    }

    /// Send a value to the other side.
    pub async fn send(&mut self, value: &S) -> Result<()> {
        #[cfg(unix)]
        {
            let mut sender =
                SingleObjectSender::new(self.fd.as_raw_handle(), value, Stream::IS_BLOCKING);
            self.fd.blocking_write(|| sender.send_next()).await
        }
        #[cfg(windows)]
        self.sender.send(value).await
    }

    /// Receive a value from the other side.
    ///
    /// Returns `Ok(None)` if the other side has dropped the channel.
    pub async fn recv(&mut self) -> Result<Option<R>> {
        #[cfg(unix)]
        {
            let mut receiver =
                unsafe { SingleObjectReceiver::new(self.fd.as_raw_handle(), Stream::IS_BLOCKING) };
            self.fd.blocking_read(|| receiver.recv_next()).await
        }
        #[cfg(windows)]
        self.receiver.recv().await
    }

    /// Send a value from the other side and wait for a response immediately.
    ///
    /// If the other side closes the channel before responding, an error is returned.
    pub async fn request(&mut self, value: &S) -> Result<R> {
        self.send(value).await?;
        self.recv().await?.ok_or_else(|| {
            Error::new(
                ErrorKind::UnexpectedEof,
                "The subprocess exitted before responding to the request",
            )
        })
    }

    pub fn into_sender(self) -> Sender<Stream, S> {
        #[cfg(unix)]
        unsafe {
            Sender::from_stream(self.fd)
        }
        #[cfg(windows)]
        self.sender
    }

    pub fn into_receiver(self) -> Receiver<Stream, R> {
        #[cfg(unix)]
        unsafe {
            Receiver::from_stream(self.fd)
        }
        #[cfg(windows)]
        self.receiver
    }
}

impl<Stream: AsyncStream, S: Object, R: Object> TryFrom<crate::Duplex<S, R>>
    for Duplex<Stream, S, R>
{
    type Error = Error;
    fn try_from(value: crate::Duplex<S, R>) -> Result<Self> {
        #[cfg(unix)]
        unsafe {
            Ok(Self::from_stream(Stream::try_new(
                SyncStream::from_raw_handle(value.into_raw_handle()),
            )?))
        }
        #[cfg(windows)]
        {
            Ok(Self {
                sender: crate::Sender(value.0.sender).try_into()?,
                receiver: crate::Receiver(value.0.receiver).try_into()?,
            })
        }
    }
}
impl<Stream: AsyncStream, S: Object, R: Object> From<Duplex<Stream, S, R>> for crate::Duplex<S, R> {
    fn from(value: Duplex<Stream, S, R>) -> Self {
        #[cfg(unix)]
        unsafe {
            Self::from_raw_handle(value.into_raw_handle())
        }
        #[cfg(windows)]
        {
            Self(Duplex {
                sender: crate::Sender::from(value.sender).0,
                receiver: crate::Receiver::from(value.receiver).0,
            })
        }
    }
}

#[cfg(unix)]
impl<Stream: AsyncStream, S: Object, R: Object> std::os::unix::io::AsRawFd
    for Duplex<Stream, S, R>
{
    fn as_raw_fd(&self) -> RawHandle {
        self.fd.as_raw_handle()
    }
}
#[cfg(unix)]
impl<Stream: AsyncStream, S: Object, R: Object> std::os::unix::io::IntoRawFd
    for Duplex<Stream, S, R>
{
    fn into_raw_fd(self) -> RawHandle {
        let fd = self.fd.as_raw_handle();
        std::mem::forget(self);
        fd
    }
}

#[cfg(unix)]
type ProcHandle = nix::unistd::Pid;
#[cfg(windows)]
type ProcHandle = crate::handles::OwnedHandle;

/// A subprocess.
pub struct Child<Stream: AsyncStream, T: Object> {
    proc_handle: ProcHandle,
    output_rx: Receiver<Stream, T>,
}

impl<Stream: AsyncStream, T: Object> Child<Stream, T> {
    fn new(proc_handle: ProcHandle, output_rx: Receiver<Stream, T>) -> Child<Stream, T> {
        Child {
            proc_handle,
            output_rx,
        }
    }

    /// Terminate the process immediately.
    pub fn kill(&mut self) -> Result<()> {
        #[cfg(unix)]
        nix::sys::signal::kill(self.proc_handle, nix::sys::signal::Signal::SIGKILL)?;
        #[cfg(windows)]
        unsafe {
            Threading::TerminateProcess(self.proc_handle.as_raw_handle(), 1).ok()?;
        }
        Ok(())
    }

    /// Get ID of the process.
    #[cfg(unix)]
    pub fn id(&self) -> pid_t {
        self.proc_handle.as_raw()
    }
    /// Get ID of the process.
    #[cfg(windows)]
    pub fn id(&self) -> RawHandle {
        self.proc_handle.as_raw_handle()
    }

    /// Wait for the process to finish and obtain the value it returns.
    ///
    /// An error is returned if the process panics or is terminated. An error is also delivered if
    /// it exits via [`std::process::exit`] or alike instead of returning a value, unless the return
    /// type is `()`. In that case, `Ok(())` is returned.
    pub async fn join(mut self) -> Result<T> {
        let mut value = self.output_rx.recv().await?;
        if let Some(void) = imp::if_void::<T>() {
            // The value should be None at this moment
            value = Some(void);
        }
        // This is synchronous, but should be really fast
        #[cfg(unix)]
        {
            let status = nix::sys::wait::waitpid(self.proc_handle, None)?;
            if let nix::sys::wait::WaitStatus::Exited(_, 0) = status {
                value.ok_or_else(|| {
                    Error::new(
                        ErrorKind::Other,
                        "The subprocess terminated without returning a value",
                    )
                })
            } else {
                Err(Error::new(
                    ErrorKind::Other,
                    format!(
                        "The subprocess did not terminate successfully: {:?}",
                        status
                    ),
                ))
            }
        }
        #[cfg(windows)]
        {
            if unsafe {
                Threading::WaitForSingleObject(
                    self.proc_handle.as_raw_handle(),
                    WindowsProgramming::INFINITE,
                )
            } == u32::MAX
            {
                return Err(Error::last_os_error());
            }
            let mut code: u32 = 0;
            unsafe {
                Threading::GetExitCodeProcess(
                    self.proc_handle.as_raw_handle(),
                    &mut code as *mut u32,
                )
                .ok()?;
            }
            if code == 0 {
                value.ok_or_else(|| {
                    Error::new(
                        ErrorKind::Other,
                        "The subprocess terminated without returning a value",
                    )
                })
            } else {
                Err(Error::new(
                    ErrorKind::Other,
                    format!("The subprocess terminated with exit code {code}"),
                ))
            }
        }
    }
}

pub(crate) async unsafe fn spawn<Stream: AsyncStream, T: Object>(
    entry: Box<dyn FnOnceObject<(RawHandle,), Output = i32>>,
) -> Result<Child<Stream, T>> {
    imp::perform_sanity_checks();

    let mut s = Serializer::new();
    s.serialize(&entry);

    let handles = s.drain_handles();

    let (mut local, child) = duplex::<Stream, (Vec<u8>, Vec<RawHandle>), T>()?;

    let process_handle;
    let receiver;

    #[cfg(unix)]
    {
        process_handle = subprocess::_spawn_child(crate::Duplex::from(child), &handles)?;
        local.send(&(s.into_vec(), handles)).await?;
        receiver = Receiver::from_stream(local.fd);
    }

    #[cfg(windows)]
    {
        process_handle = subprocess::_spawn_child(
            child.sender.as_raw_handle(),
            child.receiver.as_raw_handle(),
            &handles,
        )?;
        local.send(&(s.into_vec(), handles)).await?;
        receiver = local.receiver;
    }

    Ok(Child::new(process_handle, receiver))
}
