name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 4 * * 1'

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-native:
    timeout-minutes: 5
    runs-on: ${{ matrix.machine.os }}
    if: success() || failure()
    strategy:
      fail-fast: false
      matrix:
        libc: [gnu, musl]
        machine:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
    env:
      target: ${{ matrix.machine.arch }}-unknown-linux-${{ matrix.libc }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update nightly && rustup default nightly
      - name: Add target
        run: rustup target add $target
      - name: Test (debug)
        run: cargo test --all-features --target $target
      - name: Test (release)
        run: cargo test --all-features --target $target --release

  windows:
    timeout-minutes: 5
    runs-on: ${{ matrix.machine.os }}
    if: success() || failure()
    strategy:
      fail-fast: false
      matrix:
        machine:
          - os: windows-latest
            arch: x86_64
          - os: windows-latest
            arch: i686
          - os: windows-11-arm
            arch: aarch64
          - os: windows-11-arm
            arch: arm64ec
    env:
      host: ${{ matrix.machine.arch == 'arm64ec' && 'aarch64' || matrix.machine.arch }}-pc-windows-msvc
      target: ${{ matrix.machine.arch }}-pc-windows-msvc
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set default-host
        run: rustup set default-host $host
      - name: Install Rust
        run: rustup update nightly && rustup default nightly
      - name: Add target
        run: rustup target add $target
      - name: Test (debug)
        run: ci/cargo-save "Test (debug)" test --all-features --target $target
      - name: Test (release)
        run: ci/cargo-save "Test (release)" test --all-features --target $target --release
      - name: Upload built tests for Wine
        uses: actions/upload-artifact@v4
        with:
          name: tests-${{ env.target }}
          path: saved-jobs
          retention-days: 1

  wine:
    timeout-minutes: 5
    runs-on: ${{ matrix.machine.os }}
    needs: windows
    strategy:
      fail-fast: false
      matrix:
        machine:
          # Ubuntu needs to be recent enough to package Wine with WoW64 support
          - os: ubuntu-26.04
            rust_arch: x86_64
          - os: ubuntu-26.04
            rust_arch: i686
          - os: ubuntu-26.04-arm
            rust_arch: aarch64
          # Wine doesn't support arm64ec out of the box yet, see
          # https://bugs.winehq.org/show_bug.cgi?id=58092
          # - os: ubuntu-26.04-arm
          #   rust_arch: arm64ec
    env:
      WINEDEBUG: fixme+all,err+all  # :ferrisClueless:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install wine
        run: |
          set -exuo pipefail
          wget -O - https://dl.winehq.org/wine-builds/winehq.key | sudo gpg --dearmor -o /etc/apt/keyrings/winehq-archive.key -
          sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/resolute/winehq-resolute.sources
          sudo apt-get update
          sudo apt-get -y install winehq-staging
          export WINEPREFIX="$RUNNER_TEMP/.wine"
          echo "WINEPREFIX=$WINEPREFIX" >>"$GITHUB_ENV"
          wineboot
      - name: Download built tests
        uses: actions/download-artifact@v4
        with:
          name: tests-${{ matrix.machine.rust_arch }}-pc-windows-msvc
          path: saved-jobs
      - name: Run tests
        run: ci/run-saved-jobs

  test-stable:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    if: success() || failure()
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable && rustup default stable
      - name: Test (debug)
        run: cargo test -F tokio -F smol
      - name: Test (release)
        run: cargo test -F tokio -F smol --release

  lint:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update nightly && rustup default nightly
      - name: Install rustfmt and clippy
        run: rustup component add rustfmt clippy
      - name: Install Windows target
        run: rustup target add x86_64-pc-windows-msvc
      - name: Rustfmt
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Clippy
        run: cargo clippy --all-targets --all-features --target x86_64-pc-windows-msvc -- -D warnings
